INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL,'member','pass01!', 
			'member01@kh.or.kr',
			'닉네임1','조원찬1',  NULL, DEFAULT, DEFAULT, NULL
			, NULL, DEFAULT, DEFAULT, DEFAULT);
		
COMMIT;


UPDATE "MEMBER"
SET
	 "MEMBER_PW" = '$2a$10$m1sZd3JwzvcUyQukOiXrHOsie0s7RSvqpWLMATGy4RhyJ2DHOb47q'
WHERE
	"MEMBER_NO" = 13;

DELETE
FROM CHATROOM
WHERE CHATROOM_NO = '5';


CREATE SEQUENCE SEQ_NOTI_NO NOCACHE;