CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(150)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	VARCHAR2(30)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(10)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"CREATED_AT"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"MEMBER_DEL_BAN_FL"	CHAR(1)	DEFAULT 1	NOT NULL,
	"MEMBER_BIRTH"	DATE		NULL,
	"SELF_INTRODUCTION"	VARCHAR2(1000)		NULL,
	"MEMBER_DISCLOSURE_SCOPE"	NUMBER	DEFAULT 1	NOT NULL,
	"ADMIN"	CHAR(1)	DEFAULT 1	NOT NULL,
	"REPORT_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호(암호화)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원명(별명)';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원이름';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지 경로';
COMMENT ON COLUMN "MEMBER"."CREATED_AT" IS '가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_BAN_FL" IS '탈퇴/정지 여부 ( 1: 정상, 2: 탈퇴, 3: 정지 )';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '생년월일';
COMMENT ON COLUMN "MEMBER"."SELF_INTRODUCTION" IS '자기소개';
COMMENT ON COLUMN "MEMBER"."MEMBER_DISCLOSURE_SCOPE" IS '공개(1:공개, 2: 비공개)';
COMMENT ON COLUMN "MEMBER"."ADMIN" IS '1 : 일반, 2: 관리자';
COMMENT ON COLUMN "MEMBER"."REPORT_COUNT" IS '경고 누적 횟수';

CREATE TABLE "CHATROOM" (
	"CHATROOM_NO"	NUMBER		NOT NULL,
	"CREATED_AT"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"OPEN_MEMBER"	NUMBER		NOT NULL,
	"PARTICIPANT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATROOM"."CHATROOM_NO" IS '채팅방 번호(SEQ_CHATROOM_NO';

COMMENT ON COLUMN "CHATROOM"."CREATED_AT" IS '채팅방 생성일';

COMMENT ON COLUMN "CHATROOM"."OPEN_MEMBER" IS '개설자 회원 번호';

COMMENT ON COLUMN "CHATROOM"."PARTICIPANT" IS '참여자 회원 번호';

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MESSAGE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SEND_TIME"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"CHATROOM_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '메시지 번호';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메시지 내용';
COMMENT ON COLUMN "MESSAGE"."READ_FL" IS '읽음 여부(Y,N)';
COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '메시지 보낸 시간';
COMMENT ON COLUMN "MESSAGE"."MEMBER_NO" IS '회원번호';
COMMENT ON COLUMN "MESSAGE"."CHATROOM_NO" IS '채팅방 번호(SEQ_CHATROOM_NO';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO");

ALTER TABLE "CHATROOM" ADD CONSTRAINT "PK_CHATROOM" PRIMARY KEY (
	"CHATROOM_NO");

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO");

ALTER TABLE "CHATROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATROOM_1" FOREIGN KEY (
	"OPEN_MEMBER")
REFERENCES "MEMBER" (
	"MEMBER_NO");

ALTER TABLE "CHATROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATROOM_2" FOREIGN KEY (
	"PARTICIPANT")
REFERENCES "MEMBER" (
	"MEMBER_NO");

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
	"MEMBER_NO")
REFERENCES "MEMBER" (
	"MEMBER_NO");

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHATROOM_TO_MESSAGE_1" FOREIGN KEY (
	"CHATROOM_NO")
REFERENCES "CHATROOM" (
	"CHATROOM_NO");

